apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

namespace: development

resources:
  - ../../base

configMapGenerator:
  - name: configmap
    behavior: replace
    literals:
      - version=rpchan44/webapp-dev:main-5cd4e523c89808fe4683734b79ab8af78c3e44e5
    envs:
      - config.properties

patches:
 - path: ingress-patch.yaml
 - path: apps.yaml
