apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

namespace: development

resources:
  - ../../base

configMapGenerator:
  - name: configmap
    behavior: replace
    literals:
      - version=rpchan44/webapp-dev:main-4de2489500c54da805a829df6e9781aca0aed8ec
    envs:
      - config.properties

patches:
 - path: ingress-patch.yaml
 - path: apps.yaml
