apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

namespace: development

resources:
  - ../../base

configMapGenerator:
  - name: configmap
    behavior: replace
    literals:
      - version=rpchan44/webapp-dev:main-8d31b1be0e4071dffee5789432d99f8c063a955e
    envs:
      - config.properties

patches:
 - path: ingress-patch.yaml
 - path: apps.yaml
