apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

namespace: development

resources:
  - ../../base

configMapGenerator:
  - name: configmap
    behavior: replace
    literals:
      - version=rpchan44/webapp:v1.0-dev:main-39f953166f19f8481c922d011816bf5735f6e570
    envs:
      - config.properties

patches:
 - path: ingress-patch.yaml
 - path: apps.yaml
