apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: prod-

namespace: production

resources:
  - ../../base

configMapGenerator:
  - name: configmap
    behavior: replace
    literals:
      - version=rpchan44/webapp:v1.0-prod:main-4edfa68ec5cc6a0ba1a942d40313ae88d84019e3
    envs:
      - config.properties

patches:
 - path: ingress-patch.yaml
 - path: apps.yaml
